import { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
    return [
        {
            url: "https://mennr.tech/",
            // lastModified: new Date().toISOString().split("T")[0],
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.9,
        },
        {
            url: "https://mennr.tech/who-we-are",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.9,
        },
        {
            url: "https://mennr.tech/who-we-help",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/what-we-do",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/solutions",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 1,
        },
        {
            url: "https://mennr.tech/login",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/automotive-business",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/automotive-business/auto-body",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/automotive-business/tire-shops",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/automotive-business/tuners",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/automotive-business/diesel-shops",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/automotive-business/service-shops",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/automotive-business/community-auto-shops",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/automotive-business/automotive-restorations",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/automotive-business/carwashes",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/skilled-trades-businesses",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/skilled-trades-businesses/plumbers",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/skilled-trades-businesses/painters",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/skilled-trades-businesses/Concrete-and-paving",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/skilled-trades-businesses/contactors",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/skilled-trades-businesses/electricians",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/skilled-trades-businesses/HVAC",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/skilled-trades-businesses/cleaning-services",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/skilled-trades-businesses/roofers",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/skilled-trades-businesses/solar-installation",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/real-estate",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/real-estate/house-flippers",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/real-estate/property-managers",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/real-estate/brokers",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/real-estate/moving-companies",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/personal-care-businesses",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/personal-care-businesses/hair-salons",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/personal-care-businesses/barbers",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/personal-care-businesses/nail-salons",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/personal-care-businesses/spas",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/personal-care-businesses/estheticians",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/personal-care-businesses/tanning-salons",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/personal-care-businesses/gyms",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/personal-care-businesses/tattoo-shops",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/personal-care-businesses/yoga-studios",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/landscaping-businesses",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/landscaping-businesses/tree-removal",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/landscaping-businesses/lawn-maintenance",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/landscaping-businesses/turf-installation",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/landscaping-businesses/pool-installation",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/landscaping-businesses/irrigation",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/landscaping-businesses/snow-removal",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/landscaping-businesses/excavation",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/landscaping-businesses/pest-control",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/landscaping-businesses/fence-installation",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/other-small-businesses",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/other-small-businesses/restaurants",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/other-small-businesses/outdoor-activities",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/other-small-businesses/hotels",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/other-small-businesses/law-firms",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/other-small-businesses/tourism",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/who-we-help/other-small-businesses/retail-shops",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },

        {
            url: "https://mennr.tech/what-we-do/website-design-and-development",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/what-we-do/seo",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/what-we-do/map-ads",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/what-we-do/social-media-management",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/what-we-do/meta-ads",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/what-we-do/google-ads",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/what-we-do/review-management",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/what-we-do/reputation-management",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/what-we-do/google-business-profile",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/what-we-do/business-listings",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/what-we-do/direct-mail-ads",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/what-we-do/strategic-planning",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/privacy-policy",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/ccpa",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/do-not-sell-or-share",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/privacy-form",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/booking-confirmed",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
        {
            url: "https://mennr.tech/ccpa-confirmation",
            lastModified: "2024-01-25",
            changeFrequency: "monthly",
            priority: 0.5,
        },
    ];
}
